version: "3.9"

services:
  lrweb:
    build:
      context: ./linear-regression-web
      dockerfile: Dockerfile
    container_name: web_app_lr
    ports:
      - "5000:5000"
    networks:
      - app_bridge

  lrsrv:
    build:
      context: ./linear-regression
      dockerfile: Dockerfile
    container_name: srv_lr
    ports:
      - "3000:3000"
    networks:
      - app_bridge

networks:
  app_bridge:
    driver: bridge
